config/routes.rb
Rails.application.routes.draw do

  root :to => 'rate_calculators#new'

  get 'rate_calculators/new'
  get 'rate_calculators/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/finance_calculation.rb
module FinanceCalculation
  class Loan
    attr_accessor :duration
    attr_accessor :amount
    attr_accessor :nominal_rate
    attr_reader :monthly_rate
    attr_reader :currency_protection
    attr_reader :structure_fee
    attr_reader :principal
    attr_reader :fee
    
    def initialize(options = {})
      initialize_options(options)
      @principal = principal_calculation
      @monthly_rate = @nominal_rate / 100 / 12
    end

    def pmt(options = {})
      future_value = options.fetch(:future_value, 0)
      type = options.fetch(:type, 0)
      ((@amount * interest(@monthly_rate, @duration) - future_value ) / ((1.0 + @monthly_rate * type) * fvifa(@monthly_rate, duration)))
    end
    
    protected

      def pow1pm1(x, y)
        (x <= -1) ? ((1 + x) ** y) - 1 : Math.exp(y * Math.log(1.0 + x)) - 1
      end

      def pow1p(x, y)
        (x.abs > 0.5) ? ((1 + x) ** y) : Math.exp(y * Math.log(1.0 + x))
      end

      def interest(monthly_rate, duration)
        pow1p(monthly_rate, duration)
      end

      def fvifa(monthly_rate, duration)
        (monthly_rate == 0) ? duration : pow1pm1(monthly_rate, duration) / monthly_rate
      end

    private

      def initialize_options(options)
        @nominal_rate = options.fetch(:nominal_rate).to_f
        @duration = options.fetch(:duration).to_f
        @amount = options.fetch(:amount).to_f
        @structure_fee = options.fetch(:structure_fee, 5).to_f
        @currency_protection = options.fetch(:currency_protection, 3).to_f
        @fee = options.fetch(:fee, 0).to_f
      end

      def principal_calculation
        amount * (1 - currency_protection/100 - structure_fee / 100 ) - fee * duration
      end

      def newton_raphson(f, f_deriv, start, precision = 5)
        k_plus_one = start
        k = 0.0
        while ((k - 1) * 10**precision).to_f.floor !=  ((k_plus_one - 1) * 10**precision).to_f.floor
          k = k_plus_one
          k_plus_one = k - f.call(k) / f_deriv.call(k).abs
        end
        k_plus_one
      end
  end
end

app/controllers/rate_calculators_controller.rb
class RateCalculatorsController < ApplicationController
  include FinanceCalculation

  def index
    # unless params["principal_balance"] && params["duration"] && params["wac"] 
    #   flash[:errors] = "Please enter all required fields.."
    #   redirect_to rate_calculators_new_path and return true
    # else
      @principal_balance = params["unpaid_principal_balance"].to_f #params["principal_balance"].to_f
      @wac = params["wac"].to_f
      @duration = params["remaining_amortization_term"].to_f #params["duration"].to_i 
      @servicing_fee = params["servicing_fee"].to_f
      @remaining_amortization_term = params["remaining_amortization_term"].to_f
      @remaining_term_to_maturity = params["remaining_term_to_maturity"].to_i
      @loss_assumption = params["loss_assumption"].to_f
      @prepayment_assumption = params["prepayment_assumption"].to_f
      @price_paid = params["price_paid"].to_f

      @scheduled_interest = calculate_scheduled_interest(@principal_balance, @wac).round
      @scheduled_payment = calculate_scheduled_payment
      @scheduled_principal = calculate_scheduled_principal
      @ending_perf_balance = ending_performing_balance
      set_arrays_of_calculations
    # end
  end

  def new; end

  private

  def calculate_scheduled_interest(principal_balance, wac)
    (principal_balance * wac)/(12 * 100) rescue 0
  end

  def calculate_scheduled_payment
    FinanceCalculation::Loan.new(nominal_rate: @wac, duration: @duration, amount: @principal_balance, structure_fee: @servicing_fee).pmt
  end

  def calculate_scheduled_principal
    (calculate_scheduled_payment - calculate_scheduled_interest(@principal_balance, @wac)) rescue 0
  end

  def ending_performing_balance
    @principal_balance - @scheduled_principal
  end

  def calculate_servicing_fee(perf_principal)
    (perf_principal*@servicing_fee)/(12*100) rescue 0 
  end

  def calculate_default(perf_principal)
    (perf_principal*@loss_assumption)/(12*100) rescue 0
  end

  def calculate_received_interest(scheduled_interest, servicing_fee)
    scheduled_interest - servicing_fee
  end

  def calculate_received_principal(prepayment, scheduled_principal)
    (prepayment + scheduled_principal) rescue 0
  end

  def calculate_prepayment(begining_perf_principal, scheduled_principal)
    minus_amt = begining_perf_principal - scheduled_principal
    monthly = 0.08 # 1/12
    prepay_assumption = (1-@prepayment_assumption/100)
    ((100*(minus_amt)*(1-(prepay_assumption)**(monthly))+0.5)/100) rescue 0
  end

  def calculate_cash_received(principal_received, interest_received)
    (principal_received + interest_received) rescue 0
  end

  def set_arrays_of_calculations
    @payments = []
    @interests = []
    @principals = []
    @end_perf_balances = []
    @servicing_fees = []
    @received_interests = []
    @prepayments = []
    @defaults = []
    @principal_received = []
    @cash_received = []

    for i in(0..@duration)
      if i==0
        @payments << @principal_balance # begining principle
        @interests << calculate_scheduled_interest(@principal_balance, @wac) # scheduled interest
        @principals << @scheduled_principal # Scheduled Principal
        @servicing_fees << calculate_servicing_fee(@principal_balance) #servicing_fees
        @end_perf_balances << @ending_perf_balance # Ending perf balance
        @received_interests << calculate_received_interest(@interests[i], @servicing_fees[i]) #received_interest
        @prepayments << calculate_prepayment(@principal_balance, @scheduled_principal) # prepayment
        @defaults << calculate_default(@principal_balance) #calculate default
        @principal_received << calculate_received_principal(@prepayments[0], @scheduled_principal) # principal received
        @cash_received << calculate_cash_received(@principal_received[0], @received_interests[0])
      else
        @payments << @end_perf_balances[i-1]
        @interests << calculate_scheduled_interest(@payments[i], @wac)
        @principals << (@scheduled_payment - @interests[i])
        @servicing_fees << calculate_servicing_fee(@payments[i])
        @defaults << calculate_default(@payments[i])
        @end_perf_balances << (@payments[i] - @principals[i])
        @received_interests << calculate_received_interest(@interests[i], @servicing_fees[i])
        @prepayments << calculate_prepayment(@payments[i], @principals[i])
        @principal_received << calculate_received_principal(@prepayments[i], @principals[i])
        @cash_received << calculate_cash_received(@principal_received[i], @received_interests[i])
      end 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rate_calculators_helper.rb
module RateCalculatorsHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-lg-start">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2021 Copyright:
    <a class="text-dark">Lendtrade.com</a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "LendTrade", root_path, class: "navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LandTrade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
      <div class="container">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: "alert alert-info" %>
        <% end %> 
        <%=yield %>
      </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/rate_calculators/index.html.erb
<h2>Finance Calculations</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Months</th>
      <th scope="col">Beginning Performing Principal</th>
      <th scope="col">Scheduled Payment</th>
      <th scope="col">Scheduled Interest</th>
      <th scope="col">Servicing Fee</th>
      <th scope="col">Scheduled Principal</th>
      <th scope="col">Prepayments</th>
      <th scope="col">Defaults</th>
      <th scope="col">Principal Received</th>
      <th scope="col">Ending Performing Balance</th>
      <th scope="col">Principal Received</th>
      <th scope="col">Interest Received</th>
      <th scope="col">Cash Received</th>
    </tr>
  </thead>
  <tbody>
    <% (1..(@duration)).each do |month|  %>
      <tr>
        <td><%= month %></td>
        <td><%= @payments[month - 1].round %></td>
        <td><%= @scheduled_payment.round %></td>
        <td><%= @interests[month - 1].round %></td>
        <td><%= @servicing_fees[month - 1].round %></td>
        <td><%= @principals[month - 1].round %></td>
        <td><%= @prepayments[month-1].round %></td>
        <td><%= @defaults[month - 1].round %></td>
        <td><%= @principal_received[month -1].round %></td>
        <td><%= @end_perf_balances[month - 1].round %></td>
        <td><%= @principal_received[month -1].round %></td>
        <td><%= @received_interests[month - 1].round %></td>
        <td><%= @cash_received[month - 1].round %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rate_calculators/new.html.erb
<div>
  <h2>Enter values here..</h2>
</div>
<div> 
  <%= form_tag(rate_calculators_index_path, method: :get) do %>
    <div class="form-group row">
      <label for="inputPassword" class="col-2 col-form-label">Unpaid Principal Balance</label>
      <div class="col-10">
        <%= text_field_tag :unpaid_principal_balance %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputPassword" class="col-2 col-form-label">Weighted Average Coupan(WAC)</label>
      <div class="col-10">
        <%= text_field_tag :wac %>
      </div>
    </div>
    
    <div class="form-group row">
      <label for="inputPassword" class="col-2 col-form-label">Servicing Fee</label>
      <div class="col-10">
        <%= text_field_tag :servicing_fee %>
      </div>
    </div>
    
    <div class="form-group row">
      <label for="inputPassword" class="col-2 col-form-label">Remaining Amortization Term</label>
      <div class="col-10">
        <%= text_field_tag :remaining_amortization_term %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputPassword" class="col-2 col-form-label">Remaining Term to Maturity</label>
      <div class="col-10">
        <%= text_field_tag :remaining_term_to_maturity %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputPassword" class="col-2 col-form-label">Loss Assumption</label>
      <div class="col-10">
        <%= text_field_tag :loss_assumption %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputPassword" class="col-2 col-form-label">Prepayment Assumption</label>
      <div class="col-10">
        <%= text_field_tag :prepayment_assumption %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputPassword" class="col-2 col-form-label">Price Paid vs PAR (Par = 100)</label>
      <div class="col-10">
        <%= text_field_tag :price_paid %>
      </div>
    </div>

    <div class="form-group row">
      <label for="inputPassword" class="col-2 col-form-label"></label>
      <div class="col-10">
        <button class="btn btn-success">Submit</button>
      </div>                    
    </div>
  <% end %>
</div>